version: "3"
services:
  web:
    image: emilevauge/whoami
    networks:
      - default
      - traefik-net
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:whoami.traefik.local"
networks:
  traefik-net:
    external: true
